
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 10;
  public static final int CHAR = 5;
  public static final int LPAREN = 15;
  public static final int REPEAT = 24;
  public static final int INT = 3;
  public static final int ARRAY = 33;
  public static final int MINUS = 27;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 36;
  public static final int CHARACTER_LITERAL = 37;
  public static final int SEMICOLON = 9;
  public static final int IS = 29;
  public static final int AND = 31;
  public static final int LT = 18;
  public static final int OR = 32;
  public static final int COMMA = 11;
  public static final int ISNOT = 30;
  public static final int DIV = 28;
  public static final int PLUS = 26;
  public static final int NULL_LITERAL = 38;
  public static final int QUOTE = 17;
  public static final int IF = 21;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int error = 1;
  public static final int VOID = 20;
  public static final int EQ = 14;
  public static final int LBRACK = 7;
  public static final int FLOATING_POINT_LITERAL = 35;
  public static final int LBRACE = 12;
  public static final int ELSE = 22;
  public static final int RBRACK = 8;
  public static final int WHILE = 23;
  public static final int FLOAT = 6;
  public static final int RBRACE = 13;
  public static final int LONG = 4;
  public static final int GT = 19;
  public static final int INTEGER_LITERAL = 34;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "INT",
  "LONG",
  "CHAR",
  "FLOAT",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "QUOTE",
  "LT",
  "GT",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "REPEAT",
  "RETURN",
  "PLUS",
  "MINUS",
  "DIV",
  "IS",
  "ISNOT",
  "AND",
  "OR",
  "ARRAY",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "NULL_LITERAL"
  };
}
